resources:
  containers:
  - container: mono_container
    image: mono

pool:
  vmImage: 'ubuntu-16.04'

container: mono_container

steps:
- script: |
    sudo apt-get install -y nuget
    nuget restore HedraTests/HedraTests.csproj -PackagesDirectory packages
    (mcs prepare_testing.cs && mono prepare_testing.exe && rm prepare_testing.exe)
    rm Hedra/Hedra.csproj
    mv Hedra/Hedra.csproj.test Hedra/Hedra.csproj
  displayName: 'Prepare testing environment.'

- script: |
    xbuild HedraTests/HedraTests.csproj
  displayName: 'Build project.'

- script: |
    mono "packages/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe" "HedraTests/bin/Debug/HedraTests.dll" -result="./results.xml"
  displayName: 'Run tests.'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/results*.xml' 
    searchFolder: '$(System.DefaultWorkingDirectory)'
    buildPlatform: 'Mono x64'
    publishRunAttachments: true