resources:
  containers:
  - container: mono_container
    image: mono

pool:
  vmImage: 'ubuntu-16.04'

container: mono_container

steps:
- script: |
    sudo apt-get install -y nuget
    nuget restore HedraTests/HedraTests.csproj -PackagesDirectory packages
    (mcs prepare_testing.cs && mono prepare_testing.exe && rm prepare_testing.exe)
    rm Hedra/Hedra.csproj
    mv Hedra/Hedra.csproj.test Hedra/Hedra.csproj
  displayName: 'Prepare testing environment.'

- script: |
    xbuild HedraTests/HedraTests.csproj
  displayName: 'Build project.'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**/HedraTests*.dll/**'

- task: PublishTestResults@2
  condition: true
  inputs:
    testRunner: NUnit
    testResultsFiles: '**/*.xml' 
    searchFolder: '$(System.DefaultWorkingDirectory)'
    publishRunAttachments: true