resources:
  containers:
  - container: mono_container
    image: mono

pool:
  vmImage: 'ubuntu-16.04'

container: mono_container

steps:
- script: |
    sudo apt-get install -y nuget
    nuget restore HedraTests/HedraTests.csproj -PackagesDirectory packages
  displayName: 'Prepare testing environment.'

- script: |
    mkdir release
    xbuild /p:Configuration=Release Hedra/Hedra.csproj
  displayName: 'Build project.'

- task: CopyFiles@2
  displayName: 'Copy Files to Release Dir'
  inputs:
    SourceFolder: Hedra/bin/Release/

    Contents: |
     *.db
     Hedra.exe
     *.dll
     86/**
     x64/**
     Translations/**
     Modules/**

    TargetFolder: ./release

- script: |
    cd release
    mono Hedra.exe --dummy-mode