resources:
  containers:
  - container: mono_container
    image: mono

pool:
  vmImage: 'ubuntu-16.04'

container: mono_container

steps:
- script: |
    sudo apt-get install -y nuget
    nuget restore HedraTests/HedraTests.csproj -PackagesDirectory packages
  displayName: 'Prepare testing environment.'

- script: |
    xbuild Hedra/Hedra.csproj
  displayName: 'Build project.'

- script: |
    mono Hedra.exe --dummy-mode