image: codedevote/dotnet-mono

pipelines:
  default:
    - step:
        name: Run tests.
        deployment: production
        script:
          - nuget restore HedraTests/HedraTests.csproj -PackagesDirectory packages
          - chmod 777 prepare_testing.sh
          - ./prepare_testing.sh
          - rm Hedra/Hedra.csproj
          - mv Hedra/Hedra.csproj.test Hedra/Hedra.csproj
          - xbuild HedraTests/HedraTests.csproj
          - mkdir "./test-results"
          - mono "packages/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe" "HedraTests/bin/Debug/HedraTests.dll" -result="./test-results/results.xml"