namespace Hedra.Engine.Steamworks
{
    public enum Achievement : int
    {
        ACH_LEARN_ASSASSIN,
        ACH_LEARN_NINJA,
        ACH_LEARN_DRUID,
        ACH_LEARN_HUNTER,
        ACH_LEARN_BERSERKER,
        ACH_LEARN_PALADIN,
        ACH_LEARN_SCOUT,
        ACH_LEARN_NECROMANCER,
        ACH_JACK_OF_ALL_TRADES,
        ACH_DIMENSION_TRAVELLER,
        ACH_SPENDTHRIFT,
        ACH_LESSON_LEARNED,
        ACH_BED_THIEF,
        ACH_BEE_MOVIE,
        ACH_GOOD_SAMARITAN,
        ACH_FASHIONABLE,
        ACH_FISHING_MASTER,
        ACH_CHEF,
        ACH_FLUID_DYNAMICS,
        ACH_IMMORTAL,
        ACH_PYROMANIAC,
        ACH_SOUL_REAPER,
        ACH_DEEP_CUT
    }
}