using System.Reflection;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

[assembly: Obfuscation(Exclude = false, StripAfterObfuscation = true, Feature = "+rename(mode=reversible,flatten=false,password='$_G+{M=U85aRq5');")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Engine.ClassSystem'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Engine.ModuleSystem'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Engine.EntitySystem'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Engine.EntitySystem.BossSystem'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Engine.StructureSystem'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Engine.StructureSystem.VillageSystem'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Engine.StructureSystem.VillageSystem.Builders'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Engine.StructureSystem.VillageSystem.Templates'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Engine.Player'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.API'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.AISystem'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.AISystem.Behaviours'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.BiomeSystem'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.WeaponSystem'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.EntitySystem'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Components'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Rendering'):-rename")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('Hedra.Sound'):-rename")]
