
namespace Hedra.Engine.CacheSystem
{
    public enum CacheItem
    {
        AppleTrees,
        CypressTrees,
        PineTrees,
        DeadTrees,
        OakTrees,
        Rock,
        TallTrees,
        Campfire,
        Bushes,
        Fern,
        Grass,
        Wheat,
        Cloud,
        Farm,
        BerryBush,
        AttentionIcon,
        Berries,
        Mat,
        KnockedIcon,
        SleepingIcon,
        BossIcon,
        GraveyardIcon,
        VillageIcon,
        MerchantIcon,
        CampfireIcon,
        FearIcon,
        GiantTree,
        Grave,
        Mausoleum,
        Obelisk,
        MerchantCart,
        CampfireTent,
        CampfireRoaster,
        CampfireLogs,
        Mushroom,
        MaxEnums
    }
}
