# Items
STONE_ARROW = 'StoneArrow'
GLASS_FLASK = 'GlassFlask'
WOODEN_BOWL = 'WoodenBowl'
BERRY = 'Berry'
BOAT = 'Boat'
DEXTERITY_POTION = 'StaminaPotion'
STRENGTH_POTION = 'StrengthPotion'
SPEED_POTION = 'SpeedPotion'
PUMPKIN_PIE_RECIPE = 'PumpkinPieRecipe'
COOKED_MEAT_RECIPE = 'CookedMeatRecipe'
HEALTH_POTION_RECIPE = 'HealthPotionRecipe'
CORN_SOUP_RECIPE = 'CornSoupRecipe'
FISHING_ROD = 'FishingRod'
BAIT = 'Bait'
RAW_TROUT = 'RawTrout'
RAW_SALMON = 'RawSalmon'
RAW_FISH = 'RawFish'
HEALTH_POTION = 'HealthPotion'
FARMER_HAT = 'FarmerHat'
FARMING_RAKE = 'FarmingRake'
COMPANION_COW = 'CompanionCow'
ANIMAL_FOOD = 'AnimalFood'
MILK_BOTTLE = 'MilkBottle'
HOLDING_BAG = 'HoldingBag'

# Attributes
PRICE_ATTRIBUTE = 'Price'
AMOUNT_ATTRIBUTE = 'Amount'
