namespace Hedra.Items
{
    public enum EquipmentType
    {
        None,
        Sword,
        Axe,
        Hammer,
        Bow,
        Knife,
        Claw,
        Katar,
        DoubleBlades,
        Helmet,
        Chestplate,
        Pants,
        Boots,
        Pet,
        Vehicle,
        Ring,
        Staff,
        Recipe,
        Potion,
        Misc,
        FishingRod,
        HoldableObject,
        Ammo
    }
}
