namespace Hedra.Items
{
    public enum ItemType
    {
        None,
        Berry,
        Gold,
        Glider,
        Pumpkin,
        GlassFlask,
        WoodenBowl,
        PumpkinPieRecipe,
        CookedMeatRecipe,
        HealthPotionRecipe,
        MushroomStewRecipe,
        CornSoupRecipe,
        Corn,
        ChristmasHat,
        FarmerHat,
        FarmingRake,
        Boat,
        Mushroom,
        Timber,
        Pebble,
        HealthPotion,
        StoneArrow,
        WoodenStick,
        SteelArrow,
        Cabbage,
        Onion,
        Carrot,
        Peas,
        Tomato,
        Bait,
        MaxEnums
    }
}
