name: Publish Hedra

on: [workflow_dispatch]

jobs:
  deploy:
    name: Publish on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.HEDRA_CI }}
        submodules: true
      
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '6.0.100'

    - name: Build Dependencies windows
      if: matrix.os == 'windows-latest'
      shell: bash
      run: ./build-deps-windows.sh

    - name: Build Dependencies ubuntu
      if: matrix.os == 'ubuntu-latest'
      shell: bash  
      run: sudo ./build-deps-linux.sh

    - name: Publish on windows
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        ./scripts/publish.sh win-x64
        ./scripts/publish.sh win-x86
        mkdir Hedra/bin/Release/assets/
        cp Hedra/bin/Release/netcoreapp6.0/win-x64/data1.db Hedra/bin/Release/assets/data1.db
        cp Hedra/bin/Release/netcoreapp6.0/win-x64/data2.db Hedra/bin/Release/assets/data2.db
        cp Hedra/bin/Release/netcoreapp6.0/win-x64/data3.db Hedra/bin/Release/assets/data3.db

    - name: Publish on ubuntu
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        cat ./scripts/publish.sh | bash -s linux-x64

    #- uses: actions/upload-artifact@v1
    #  name: Upload ubuntu
    #  if: matrix.os == 'ubuntu-latest'
    #  with:
    #    name: hedra-linux-x64
    #    path: Hedra/bin/Release/netcoreapp6.0/linux-x64/publish

    #- uses: actions/upload-artifact@v1
    #  name: Upload ubuntu
    #  if: matrix.os == 'ubuntu-latest'
    #  with:
    #    name: hedra-linux-x86
    #    path: Hedra/bin/Release/netcoreapp6.0/linux-x86/publish

    #- uses: actions/upload-artifact@v1
    #  name: Upload windows x64
    #  if: matrix.os == 'windows-latest'
    #  with:
    #    name: hedra-win-x64
    #    path: Hedra/bin/Release/netcoreapp6.0/win-x64/publish

    #- uses: actions/upload-artifact@v1
    #  name: Upload windows x86
    #  if: matrix.os == 'windows-latest'
    #  with:
    #    name: hedra-win-x86
    #    path: Hedra/bin/Release/netcoreapp6.0/win-x86/publish

    #- uses: actions/upload-artifact@v1
    #  name: Upload assets
    #  if: matrix.os == 'windows-latest'
    #  with:
    #    name: hedra-assets
    #    path: Hedra/bin/Release/assets

    - uses: game-ci/steam-deploy@v1
      with:
        username: ${{ secrets.STEAM_USERNAME }}
        password: ${{ secrets.STEAM_PASSWORD }}
        configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
        ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
        ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
        appId: 1009960
        buildDescription: ${{ github.sha }}
        rootPath: Hedra/bin/Release
        depot2Path: assets
        depot3Path: netcoreapp6.0/win-x86/publish
        depot4Path: netcoreapp6.0/win-x64/publish
        depot5Path: netcoreapp6.0/linux-x64/publish
        releaseBranch: test
