name: Hedra CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.HEDRA_CI }}
        submodules: true
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0

    - name: Build Dependencies
      shell: bash
      run: chmod +x build-deps.sh && ./build-deps.sh
      
    - name: Build Solution
      run: dotnet test -c Release "Project Hedra.sln"

    - uses: actions/upload-artifact@v1
      with:
        name: Hedra-${{ matrix.os }}
        path: Hedra/bin/netcoreapp3.1/Release/
