name: Hedra CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.HEDRA_CI }}
        submodules: true
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
    - name: Restore Hedra packages
      run: dotnet restore Hedra/Hedra.csproj --packages packages
    - name: Restore HedraTests packages
      run: dotnet restore HedraTests/HedraTests.csproj --packages packages
    - name: Restore AssetBuilder packages 
      run: dotnet restore AssetBuilder/AssetBuilder.csproj --packages packages
    - name: Build Dependencies
      shell: bash
      run: ./build-deps.sh
    - name: Build Solution
      run: dotnet msbuild -p:Configuration=Release
    - name: Run tests
      run: ./packages/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe HedraTests/bin/Release/HedraTests.dll
      shell: bash
