name: Hedra CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.HEDRA_CI }}
        submodules: true
      
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '6.0.x'

    - name: Build Dependencies windows
      if: matrix.os == 'windows-latest'
      shell: bash
      run: ./build-deps-windows.sh
      
    - name: Build Dependencies ubuntu
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: sudo ./build-deps-linux.sh

    - name: Build and Test solution
      run: dotnet test -c Release "Project Hedra.sln"

    - uses: actions/upload-artifact@v1
      with:
        name: Hedra-${{ matrix.os }}
        path: Hedra/bin/netcoreapp6.0/Release/
