name: Hedra CI

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, windows-2019]
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore Hedra packages
      run: nuget restore Hedra/Hedra.csproj -PackagesDirectory packages
    - name: Restore HedraTests packages
      run: nuget restore HedraTests/HedraTests.csproj -PackagesDirectory packages
    - name: Restore AssetBuilder packages 
      run: nuget restore AssetBuilder/AssetBuilder.csproj -PackagesDirectory packages
    - name: Build Solution
      run: dotnet msbuild
