name: Hedra CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.HEDRA_CI }}
        submodules: true
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
      
    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5
      
    - name: Restore Hedra packages
      run: nuget restore Hedra/Hedra.csproj -PackagesDirectory packages
      
    - name: Restore HedraTests packages
      run: nuget restore HedraTests/HedraTests.csproj -PackagesDirectory packages
      
    - name: Restore AssetBuilder packages 
      run: nuget restore AssetBuilder/AssetBuilder.csproj -PackagesDirectory packages
      
    - name: Build Dependencies
      shell: bash
      run: ./build-deps.sh
      
    - name: Build Solution
      run: dotnet msbuild -p:Configuration=Release
      
    - name: Run tests
      run: ./packages/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe HedraTests/bin/Release/HedraTests.dll
      shell: bash

    - uses: actions/upload-artifact@v1
      with:
        name: Hedra-${{ matrix.os }}
        path: Hedra/bin/Release/
